"""added new field sub_date

Revision ID: 0c722afcea71
Revises: 9b226aaa2619
Create Date: 2020-11-29 17:54:16.303873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c722afcea71'
down_revision = '9b226aaa2619'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sub_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'sub_date')
    # ### end Alembic commands ###
