"""added new field sub_date

Revision ID: 9b226aaa2619
Revises: 3ddabe8af782
Create Date: 2020-11-29 17:51:46.632915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b226aaa2619'
down_revision = '3ddabe8af782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sub_date', sa.DateTime(), nullable=False))
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'sub_date')
    # ### end Alembic commands ###
